const colours: { [property: string]: string } = {
    BRAND_MAIN: '#D63238',
    BRAND_SECONDARY: '#706962',

    ERROR_COLOUR: '#C90007',
    ERROR_BACKGROUND: '#FFE5E6',

    BORDER_COLOUR: '#B3AAA1',

    GREY_BACKGROUND: '#E6E1DD',
    SHORTBREAK_BACKGROUND: '#D9FFDD',
    LONGBREAK_BACKGROUND: '#D3F7C9',
    POMODORO_BACKGROUND: '#E0DEF7',

    SHORTBREAK_COLOUR: '#085E12',
    LONGBREAK_COLOUR: '#013D08',
    POMODORO_COLOUR: '#140A6B',

    TEXT_COLOUR: '#4A4035',
};

export default colours;
